spring:
  application:
    name: @project.artifactId@

server:
  port: 9000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://192.168.12.222:9000/eureka/

  instance:
    prefer-ip-address: true

  server:
    enable-self-preservation: false
